language: java
script: 
- "mvn test"
- "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
- mvn verify -B jacoco:report coveralls:report

after_success:
- mvn clean test jacoco:report coveralls:report

jdk:
- oraclejdk8
notifications:
  slack: ti2206-2016:6BVqEMfsb6q9gJ1ziorrKQVc
  slack: semasteroids666:AT3ltV7GGySVSkrY9ZWOwKlB
